# 1. Arrays

# 1.1. Arrays con NumPy

Array es una matriz unidimensional.
NumPy es un paquete de Python creado por Travis Oliphant con propósitos científicos.
Array en NumPy consume menos memoria y por ende es más rápido que una lista de Python.


In [1]:
# Importar la librería NumPy
import numpy as np

In [3]:
# Creamos un array en Python
n_array = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11]])
n_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
# Número de dimensiones del array
n_array.ndim

2

In [5]:
# Tamaño de cada dimensión
n_array.shape

(3, 4)

In [6]:
# Número de elementos
n_array.size

12

In [7]:
# Tipo de datos
n_array.dtype.name

'int32'

# 1.2. Operaciones Matemáticas con NumPy

In [8]:
# Adición y sustracción de matrices
a = np.array( [11, 12, 13, 14])
b = np.array( [ 1, 2, 3, 4])
c = a - b
c

array([10, 10, 10, 10])

In [9]:
d = a + b
d

array([12, 14, 16, 18])

In [10]:
# Potencia de arrays.
b**2

array([ 1,  4,  9, 16])

In [11]:
# Funciones sobre los arrays.
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [12]:
# Multiplicación de matrices
A1 = np.array([[1, 1],[0, 1]]) 
A2 = np.array([[2, 0],[3, 4]])
A1

array([[1, 1],
       [0, 1]])

In [13]:
A2

array([[2, 0],
       [3, 4]])

In [14]:
A1*A2

array([[2, 0],
       [0, 4]])

In [15]:
np.dot(A1,A2)

array([[5, 4],
       [3, 4]])

# 1.3. Indexing and Slicing

In [16]:
# Seleccionamos la fila 1 y la columna 2
n_array[0,1]

1

In [17]:
# Seleccionamos la fila 1 y las 3 primeras columnas.
n_array[ 0 , 0:3 ]


array([0, 1, 2])

In [18]:
# Seleccionamos la fila 1 y todas las columnas.
n_array[ 0 , : ]


array([0, 1, 2, 3])

In [19]:
# Seleccionamos todas las filas y la columna 2.
n_array[ : , 1 ]


array([1, 5, 9])

# 1.4. Manipulación de las dimensiones de un Array

In [20]:
# Modificamos la dimensionalidad de un array llevándolo de dimensión 1xN.
n_array.ravel()


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
# Modificamos la dimensionalidad del array llevándola a 6 filas x 2 columnas.
n_array.shape = (6,2)
n_array

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [22]:
# Transpuesta de un array.
n_array.transpose()


array([[ 0,  2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9, 11]])

# 2. Análisis de datos con Pandas

 La librería Pandas desarrollada para el análisis. Fue desarrollada en NumPy. La librería Pandas trae la riqueza de R al mundo de Python. Tiene eficiente estructuras de datos para procesar los datos, unir datos y leerlos de varias fuentes.


# 2.1. Series

In [23]:
# Importar la librería Pandas desde Python.
import pandas as pd

In [24]:
# Creación de una serie a partir de 5 números aleatorios.
pd.Series(np.random.randn(5))

0    0.715445
1    0.834546
2    0.135867
3    1.681463
4    0.457292
dtype: float64

In [25]:
pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

a   -0.273748
b   -0.905747
c    0.453849
d    1.105881
e    0.784078
dtype: float64

# 2.2. Data Frames

In [26]:
# Data Frames que provienen de diccionarios de series.
d = {'c1': pd.Series(['A', 'B', 'C']),'c2': pd.Series([1., 2., 3., 4.])}
df = pd.DataFrame(d)
df

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

In [27]:
# Data Frames que provienen de diccionarios de listas.
d = {'c1': ['A', 'B', 'C', 'D'],'c2': [1.0, 2.0, 3.0, 4.0]}
df = pd.DataFrame(d)
df

c1   c2
0  A  1.0
1  B  2.0
2  C  3.0
3  D  4.0

# 2.3. Panel

In [28]:
d = {'Item1': pd.DataFrame(np.random.randn(4, 3)),'Item2': pd.DataFrame(np.random.randn(4, 2))}
pd.Panel(d)
d

{'Item1':           0         1         2
 0  0.489016  1.704929  1.136626
 1  0.570117  0.011466 -0.612345
 2  0.936624 -0.974360 -0.145132
 3 -0.018323  1.191183 -1.676015, 'Item2':           0         1
 0  1.733756  0.681354
 1 -0.557557  0.885662
 2 -0.468921  0.268261
 3  1.568265  0.079236}

# 2.4. Importar y exportar datos en formato csv

In [29]:
# Importar datos en formato csv.
d = pd.read_csv('C:/Users/AMD/Documents/Python_Introduction/Data/students.csv')

In [30]:
# Leer los primeros registros
d.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0          18.5%   
1  NORTHEASTERN NEW YORK    2012-2013            74.0          19.2%   
2  NORTHEASTERN NEW YORK    2012-2013            50.0          17.6%   
3  NORTHEASTERN NEW YORK    2012-2013            84.0          17.2%   
4  NORTHEASTERN NEW YORK    2012-2013            58.0          16.1%   

   NO. OBESE PCT OBESE  NO. OVERWEIGHT OR OBESE PCT OVERWEIGHT OR OBESE  \
0      139.0     20.8%                    263.0                   39.3%   
1       72.0     18.7%                    146.0                   37.9%   
2       67.0     23.6%                    117.0                   41.2%   
3      124.0     25.4%                    208.0                   42.5%   
4       89.0     24.7%                    147.0                   40.8%   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

In [31]:
d[0:5]['AREA NAME']

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

In [32]:
# Exportar datos de un data frame a un csv
d = {'c1': pd.Series(['A', 'B', 'C']),'c2': pd.Series([1, 2., 3., 4.])}
df = pd.DataFrame(d)
df

c1   c2
0    A  1.0
1    B  2.0
2    C  3.0
3  NaN  4.0

In [33]:
df.to_csv('C:/Users/AMD/Documents/Python_Introduction/Data/sample_data.csv')

# 2.5. Importar y exportar datos en formato xls

In [34]:
# Importar datos en formato xls.
d = pd.read_excel('C:/Users/AMD/Documents/Python_Introduction/Data/students.xls')

In [35]:
d.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0           0.185   
1  NORTHEASTERN NEW YORK    2012-2013            74.0           0.192   
2  NORTHEASTERN NEW YORK    2012-2013            50.0           0.176   
3  NORTHEASTERN NEW YORK    2012-2013            84.0           0.172   
4  NORTHEASTERN NEW YORK    2012-2013            58.0           0.161   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0      139.0      0.208                    263.0                    0.393   
1       72.0      0.187                    146.0                    0.379   
2       67.0      0.236                    117.0                    0.412   
3      124.0      0.254                    208.0                    0.425   
4       89.0      0.247                    147.0                    0.408   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

In [36]:
# Exportar datos de un data frame a un xls
df.to_excel('C:/Users/AMD/Documents/Python_Introduction/Data/sample_data.xls')

# 2.6. Importar datos en formato JSON

In [37]:
# Importar el paquete JSON.
import json

In [38]:
json_data = open('C:/Users/AMD/Documents/Python_Introduction/Data/students.json')

In [39]:
data = json.load(json_data)

In [40]:
data

{'data': [[2237,
   '5273C009-D32B-4885-B20E-136767936ADD',
   2237,
   1411498109,
   '698552',
   1411498125,
   '705890',
   '{\n}',
   '010402',
   'ALBANY',
   'RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT',
   'NORTHEASTERN NEW YORK',
   '2012-2013',
   '124',
   '18.5',
   '139',
   '20.8',
   '263',
   '39.3',
   'DISTRICT TOTAL',
   'SCHOOL DISTRICT',
   '15 MOUNTAIN RD',
   'RAVENA',
   'NY',
   '12143',
   ['{"address":"15 MOUNTAIN RD","city":"RAVENA","state":"NY","zip":"12143"}',
    '42.47227638700048',
    '-73.81484141099963',
    None,
    False]],
  [2238,
   'B5CF19C8-512B-4763-80AB-0CC83E62A5F4',
   2238,
   1411498109,
   '698552',
   1411498137,
   '705890',
   '{\n}',
   '010402',
   'ALBANY',
   'RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT',
   'NORTHEASTERN NEW YORK',
   '2012-2013',
   '74',
   '19.2',
   '72',
   '18.7',
   '146',
   '37.9',
   'ELEMENTARY',
   'SCHOOL DISTRICT',
   '15 MOUNTAIN RD',
   'RAVENA',
   'NY',
   '12143',
   ['{"address":"15

In [41]:
json_data.close()

# 3. Data Cleansing

# 3.1. Valores perdidos

In [42]:
d.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0           0.185   
1  NORTHEASTERN NEW YORK    2012-2013            74.0           0.192   
2  NORTHEASTERN NEW YORK    2012-2013            50.0           0.176   
3  NORTHEASTERN NEW YORK    2012-2013            84.0           0.172   
4  NORTHEASTERN NEW YORK    2012-2013            58.0           0.161   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0      139.0      0.208                    263.0                    0.393   
1       72.0      0.187                    146.0                    0.379   
2       67.0      0.236                    117.0                    0.412   
3      124.0      0.254                    208.0                    0.425   
4       89.0      0.247                    147.0                    0.408   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

In [80]:
# Identificar a los valores perdidos.
d['REGION'].isnull()

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...  
3240    False
3241    False
3242    False
3243    False
3244    False
3245    False
3246    False
3247    False
3248    False
3249    False
3250    False
3251    False
3252    False
3253    False
3254    False
3255    False
3256    False
3257    False
3258    False
3259    False
3260    False
3261    False
3262    False
3263    False
3264    False
3265    False
3266    False
3267    False
3268    False
3269    False
Name: REGION, dtype: bool

In [43]:
# Identificar a los valores no perdidos.
d['PCT OVERWEIGHT'].notnull()

0        True
1        True
2        True
3        True
4        True
5        True
6        True
7        True
8        True
9        True
10       True
11       True
12       True
13      False
14      False
15       True
16       True
17       True
18       True
19       True
20       True
21       True
22      False
23      False
24       True
25       True
26      False
27       True
28       True
29       True
        ...  
3240     True
3241     True
3242     True
3243     True
3244     True
3245     True
3246     True
3247     True
3248     True
3249     True
3250     True
3251     True
3252     True
3253     True
3254    False
3255     True
3256     True
3257     True
3258     True
3259     True
3260     True
3261     True
3262     True
3263     True
3264     True
3265     True
3266     True
3267     True
3268     True
3269     True
Name: PCT OVERWEIGHT, dtype: bool

In [81]:
# Cuantificar a los valores perdidos.
d['PCT OVERWEIGHT'].isnull().value_counts()

False    3078
True      192
Name: PCT OVERWEIGHT, dtype: int64

In [44]:
# Cuantificar a los valores no perdidos.
d['PCT OVERWEIGHT'].notnull().value_counts()

True     3078
False     192
Name: PCT OVERWEIGHT, dtype: int64

In [83]:
# Eliminar a los valores perdidos.
d['PCT OVERWEIGHT'].dropna()

0       0.185
1       0.192
2       0.176
3       0.172
4       0.161
5       0.202
6       0.159
7       0.174
8       0.139
9       0.163
10      0.155
11      0.169
12      0.176
15      0.130
16      0.126
17      0.136
18      0.211
19      0.219
20      0.209
21      0.143
24      0.175
25      0.214
27      0.208
28      0.222
29      0.333
30      0.163
31      0.158
32      0.180
33      0.166
34      0.116
        ...  
3239    0.152
3240    0.168
3241    0.168
3242    0.167
3243    0.161
3244    0.153
3245    0.171
3246    0.144
3247    0.124
3248    0.171
3249    0.191
3250    0.177
3251    0.212
3252    0.164
3253    0.188
3255    0.188
3256    0.181
3257    0.196
3258    0.213
3259    0.217
3260    0.214
3261    0.173
3262    0.182
3263    0.172
3264    0.160
3265    0.156
3266    0.156
3267    0.158
3268    0.152
3269    0.171
Name: PCT OVERWEIGHT, dtype: float64

In [84]:
d.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0           0.185   
1  NORTHEASTERN NEW YORK    2012-2013            74.0           0.192   
2  NORTHEASTERN NEW YORK    2012-2013            50.0           0.176   
3  NORTHEASTERN NEW YORK    2012-2013            84.0           0.172   
4  NORTHEASTERN NEW YORK    2012-2013            58.0           0.161   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0      139.0      0.208                    263.0                    0.393   
1       72.0      0.187                    146.0                    0.379   
2       67.0      0.236                    117.0                    0.412   
3      124.0      0.254                    208.0                    0.425   
4       89.0      0.247                    147.0                    0.408   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

In [45]:
# Eliminar a cualquier registro que tenga por lo menos un campo con valor perdido.
d = d.dropna(how='any')

In [87]:
d.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT  PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0           0.185   
1  NORTHEASTERN NEW YORK    2012-2013            74.0           0.192   
2  NORTHEASTERN NEW YORK    2012-2013            50.0           0.176   
3  NORTHEASTERN NEW YORK    2012-2013            84.0           0.172   
4  NORTHEASTERN NEW YORK    2012-2013            58.0           0.161   

   NO. OBESE  PCT OBESE  NO. OVERWEIGHT OR OBESE  PCT OVERWEIGHT OR OBESE  \
0      139.0      0.208                    263.0                    0.393   
1       72.0      0.187                    146.0                    0.379   
2       67.0      0.236                    117.0                    0.412   
3      124.0      0.254                    208.0                    0.425   
4       89.0      0.247                    147.0                    0.408   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...

In [46]:
# Cuantificar a los valores perdidos.
d['PCT OVERWEIGHT'].isnull().value_counts()

False    2833
Name: PCT OVERWEIGHT, dtype: int64

# 3.2. Imputar Valores Perdidos

In [48]:
# Crear un data frame en base a números aleatorios.
df = pd.DataFrame(np.random.randn(5, 3), index=['a0', 'a10','a20', 'a30', 'a40'],columns=['X', 'Y', 'Z'])
df

X         Y         Z
a0  -0.352013 -1.629371 -1.943725
a10 -0.648098 -0.922592  0.227779
a20 -1.289392  2.299702  0.515969
a30 -0.921281  1.902106 -1.360094
a40 -0.955119 -0.343794  2.431444

In [50]:
# Crear índices adicionales al data frame.
df2 = df.reindex(['a0', 'a1', 'a10', 'a11', 'a20', 'a21','a30', 'a31', 'a40', 'a41'])
df2

X         Y         Z
a0  -0.352013 -1.629371 -1.943725
a1        NaN       NaN       NaN
a10 -0.648098 -0.922592  0.227779
a11       NaN       NaN       NaN
a20 -1.289392  2.299702  0.515969
a21       NaN       NaN       NaN
a30 -0.921281  1.902106 -1.360094
a31       NaN       NaN       NaN
a40 -0.955119 -0.343794  2.431444
a41       NaN       NaN       NaN

In [51]:
# Completar los valores perdidos con ceros.
df3 = df2.fillna(0)
df3

X         Y         Z
a0  -0.352013 -1.629371 -1.943725
a1   0.000000  0.000000  0.000000
a10 -0.648098 -0.922592  0.227779
a11  0.000000  0.000000  0.000000
a20 -1.289392  2.299702  0.515969
a21  0.000000  0.000000  0.000000
a30 -0.921281  1.902106 -1.360094
a31  0.000000  0.000000  0.000000
a40 -0.955119 -0.343794  2.431444
a41  0.000000  0.000000  0.000000

In [52]:
# Completar los valores perdidos con el método “forward propagation”. Se va completar con el valor previo al nulo.
df4 = df2.fillna(method='pad')
df4

X         Y         Z
a0  -0.352013 -1.629371 -1.943725
a1  -0.352013 -1.629371 -1.943725
a10 -0.648098 -0.922592  0.227779
a11 -0.648098 -0.922592  0.227779
a20 -1.289392  2.299702  0.515969
a21 -1.289392  2.299702  0.515969
a30 -0.921281  1.902106 -1.360094
a31 -0.921281  1.902106 -1.360094
a40 -0.955119 -0.343794  2.431444
a41 -0.955119 -0.343794  2.431444

In [53]:
# Completar los valores perdidos con el promedio de la variable.
df5 = df2.fillna(df2.mean())
df5

X         Y         Z
a0  -0.352013 -1.629371 -1.943725
a1  -0.833181  0.261210 -0.025725
a10 -0.648098 -0.922592  0.227779
a11 -0.833181  0.261210 -0.025725
a20 -1.289392  2.299702  0.515969
a21 -0.833181  0.261210 -0.025725
a30 -0.921281  1.902106 -1.360094
a31 -0.833181  0.261210 -0.025725
a40 -0.955119 -0.343794  2.431444
a41 -0.833181  0.261210 -0.025725

# 3.3. Operaciones con cadenas

In [54]:
# Importar un archivo csv y leer los 5 primeros casos.
df = pd.read_csv('C:/Users/AMD/Documents/Python_Introduction/Data/students.csv')
df['AREA NAME'][0:5]

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

In [56]:
# Extraer las dos primeras palabras de los 5 primeros casos.
df['AREA NAME'][0:5].str.extract('(\w+)\s(\w+)\s(\w+)')

C:\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: FutureWarning: currently extract(expand=None) means expand=False (return Index/Series/DataFrame) but in a future version of pandas this will be changed to expand=True (return DataFrame)
  from ipykernel import kernelapp as app


0         1        2
0  RAVENA  COEYMANS  SELKIRK
1  RAVENA  COEYMANS  SELKIRK
2  RAVENA  COEYMANS  SELKIRK
3  COHOES      CITY   SCHOOL
4  COHOES      CITY   SCHOOL

In [57]:
# Filtrar casos específicos.
df[df['GRADE LEVEL'] == 'ELEMENTARY']

LOCATION CODE       COUNTY  \
1             10402       ALBANY   
4             10500       ALBANY   
7             10601       ALBANY   
10            10623       ALBANY   
13            10701       ALBANY   
16            10802       ALBANY   
19            20101     ALLEGANY   
22            21102     ALLEGANY   
25            21601     ALLEGANY   
28            22101     ALLEGANY   
31            22601     ALLEGANY   
34            22902     ALLEGANY   
37            30101       BROOME   
40            30200       BROOME   
43            30501       BROOME   
46            30601       BROOME   
49            30701       BROOME   
52            31701       BROOME   
55            40302  CATTARAUGUS   
58            40901  CATTARAUGUS   
61            41401  CATTARAUGUS   
64            42400  CATTARAUGUS   
67            43001  CATTARAUGUS   
70            43200  CATTARAUGUS   
73            50301       CAYUGA   
76            50401       CAYUGA   
79            51301       CAYUGA   
82            60301   CHAUTAUQUA   
85            60401   CHAUTAUQUA   
88            60701   CHAUTAUQUA   
...             ...          ...   
3181         660802  WESTCHESTER   
3184         660805  WESTCHESTER   
3187         660809  WESTCHESTER   
3190         660900  WESTCHESTER   
3193         661004  WESTCHESTER   
3196         661100  WESTCHESTER   
3199         661201  WESTCHESTER   
3202         661301  WESTCHESTER   
3205         661401  WESTCHESTER   
3208         661402  WESTCHESTER   
3211         661500  WESTCHESTER   
3214         661601  WESTCHESTER   
3217         661800  WESTCHESTER   
3220         661901  WESTCHESTER   
3223         661904  WESTCHESTER   
3226         661905  WESTCHESTER   
3229         662001  WESTCHESTER   
3232         662101  WESTCHESTER   
3235         662200  WESTCHESTER   
3238         662300  WESTCHESTER   
3241         662401  WESTCHESTER   
3244         662402  WESTCHESTER   
3247         670201      WYOMING   
3250         670401      WYOMING   
3253         671002      WYOMING   
3256         671201      WYOMING   
3259         671501      WYOMING   
3262         680601        YATES   
3265         680801        YATES   
3268         700000          NaN   

                                            AREA NAME                 REGION  \
1     RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
4                         COHOES CITY SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
7               SOUTH COLONIE CENTRAL SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
10              NORTH COLONIE CENTRAL SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
13            GREEN ISLAND UNION FREE SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
16                GUILDERLAND CENTRAL SCHOOL DISTRICT  NORTHEASTERN NEW YORK   
19              ALFRED ALMOND CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
22                 CANASERAGA CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
25                 FRIENDSHIP CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
28                WHITESVILLE CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
31                 WELLSVILLE CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
34           BOLIVAR-RICHBURG CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
37             CHENANGO FORKS CENTRAL SCHOOL DISTRICT        NEW YORK - PENN   
40                    BINGHAMTON CITY SCHOOL DISTRICT        NEW YORK - PENN   
43               HARPURSVILLE CENTRAL SCHOOL DISTRICT        NEW YORK - PENN   
46         SUSQUEHANNA VALLEY CENTRAL SCHOOL DISTRICT        NEW YORK - PENN   
49            CHENANGO VALLEY CENTRAL SCHOOL DISTRICT        NEW YORK - PENN   
52                    WINDSOR CENTRAL SCHOOL DISTRICT        NEW YORK - PENN   
55                             ALLEGANY-LIMESTONE CSD       WESTERN NEW YORK   
58              ELLICOTTVILLE CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
61                   HINSDALE CENTRAL SCHOOL DISTRICT       WESTERN NEW YORK   
64           

In [58]:
# Convertir a mayúsculas.
df['AREA NAME'][0:5].str.upper()

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT
3                        COHOES CITY SCHOOL DISTRICT
4                        COHOES CITY SCHOOL DISTRICT
Name: AREA NAME, dtype: object

In [59]:
# Convertir a minúsculas.
df['AREA NAME'][0:5].str.lower()

0    ravena coeymans selkirk central school district
1    ravena coeymans selkirk central school district
2    ravena coeymans selkirk central school district
3                        cohoes city school district
4                        cohoes city school district
Name: AREA NAME, dtype: object

In [60]:
# Cuantificar la cantidad de caracteres de cada elemento.
df['AREA NAME'][0:5].str.len()

0    47
1    47
2    47
3    27
4    27
Name: AREA NAME, dtype: int64

In [61]:
# Cortar en base a espacios en blanco.
df['AREA NAME'][0:5].str.split(' ')

0    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
1    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
2    [RAVENA, COEYMANS, SELKIRK, CENTRAL, SCHOOL, D...
3                     [COHOES, CITY, SCHOOL, DISTRICT]
4                     [COHOES, CITY, SCHOOL, DISTRICT]
Name: AREA NAME, dtype: object

In [63]:
# Reemplazar
df['AREA NAME'][0:5].str.replace('DISTRICT', 'DIST')

0    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
1    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
2    RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DIST
3                        COHOES CITY SCHOOL DIST
4                        COHOES CITY SCHOOL DIST
Name: AREA NAME, dtype: object

# 4. Agregación de datos

In [64]:
# Seleccionamos los 5 primeros registros de 2 campos.
d[['AREA NAME', 'COUNTY']][0:5]

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
3                      COHOES CITY SCHOOL DISTRICT  ALBANY
4                      COHOES CITY SCHOOL DISTRICT  ALBANY

In [65]:
# Partir los datos en dos grupos. Concatenarlos por posición.
p1 = d[['AREA NAME', 'COUNTY']][0:2] 
p1

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY

In [66]:
p2 = d[['AREA NAME', 'COUNTY']][2:5]
p2

AREA NAME  COUNTY
2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
3                      COHOES CITY SCHOOL DISTRICT  ALBANY
4                      COHOES CITY SCHOOL DISTRICT  ALBANY

In [115]:
pd.concat([p1,p2])

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
3                      COHOES CITY SCHOOL DISTRICT  ALBANY
4                      COHOES CITY SCHOOL DISTRICT  ALBANY

In [67]:
# Concatenar datos en base a una llave.
concatenated = pd.concat([p1,p2], keys = ['p1','p2'])
concatenated.head()

AREA NAME  COUNTY
p1 0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
   1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
p2 2  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
   3                      COHOES CITY SCHOOL DISTRICT  ALBANY
   4                      COHOES CITY SCHOOL DISTRICT  ALBANY

In [68]:
# Seleccionar la data agregada en base a una llave.
concatenated.ix['p1']

AREA NAME  COUNTY
0  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY
1  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT  ALBANY

In [69]:
# Seleccionamos un subconjunto de elementos y promediamos.
data = df[df['GRADE LEVEL'] == 'ELEMENTARY']
data.head()

LOCATION CODE  COUNTY                                        AREA NAME  \
1           10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
4           10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
7           10601  ALBANY            SOUTH COLONIE CENTRAL SCHOOL DISTRICT   
10          10623  ALBANY            NORTH COLONIE CENTRAL SCHOOL DISTRICT   
13          10701  ALBANY          GREEN ISLAND UNION FREE SCHOOL DISTRICT   

                   REGION SCHOOL YEARS  NO. OVERWEIGHT PCT OVERWEIGHT  \
1   NORTHEASTERN NEW YORK    2012-2013            74.0          19.2%   
4   NORTHEASTERN NEW YORK    2012-2013            58.0          16.1%   
7   NORTHEASTERN NEW YORK    2012-2013           145.0          17.4%   
10  NORTHEASTERN NEW YORK    2012-2013            94.0          15.5%   
13  NORTHEASTERN NEW YORK    2012-2013             NaN            NaN   

    NO. OBESE PCT OBESE  NO. OVERWEIGHT OR OBESE PCT OVERWEIGHT OR OBESE  \
1        72.0     18.7%                    146.0                   37.9%   
4        89.0     24.7%                    147.0                   40.8%   
7       169.0     20.3%                    314.0                   37.8%   
10       78.0     12.9%                    172.0                   28.4%   
13       15.0     35.7%                     15.0                   35.7%   

   GRADE LEVEL        AREA TYPE  STREET ADDRESS          CITY STATE  ZIP CODE  \
1   ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD        RAVENA    NY   12143.0   
4   ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST        COHOES    NY   12047.0   
7   ELEMENTARY  SCHOOL DISTRICT  102 LORALEE DR        ALBANY    NY   12205.0   
10  ELEMENTARY  SCHOOL DISTRICT  91 FIDDLERS LN        LATHAM    NY   12110.0   
13  ELEMENTARY  SCHOOL DISTRICT  171 HUDSON AVE  GREEN ISLAND    NY   12183.0   

                                           Location 1  
1   15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...  
4   7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...  
7   102 LORALEE DR\nALBANY, NY 12205\n(42.73352407...  
10  91 FIDDLERS LN\nLATHAM, NY 12110\n(42.72935391...  
13  171 HUDSON AVE\nGREEN ISLAND, NY 12183\n(42.74...

In [72]:
data['NO. OBESE'][0:2]

1    72.0
4    89.0
Name: NO. OBESE, dtype: float64

In [73]:
data['NO. OBESE'].mean()

213.4159378036929

In [74]:
# La suma total.
data['NO. OBESE'].sum()

219605.0

In [75]:
# Valor máximo.
data['NO. OBESE'].max()

48843.0

In [76]:
# Valor mínimo.
data['NO. OBESE'].min()

5.0

In [77]:
# Desviación Estándar.
data['NO. OBESE'].std()

1690.3831128098109

In [78]:
# Conteo.
data = df[(df['GRADE LEVEL'] == 'ELEMENTARY') &(df['COUNTY'] == 'DELAWARE')]
data['COUNTY'].count()

19

In [127]:
data['GRADE LEVEL'].count()

19

In [79]:
# Crear datos
grade_lookup = {'GRADE LEVEL': pd.Series(['ELEMENTARY','MIDDLE/HIGH', 'MISC']),'LEVEL': pd.Series([1, 2, 3])}
grade_lookup

{'GRADE LEVEL': 0     ELEMENTARY
 1    MIDDLE/HIGH
 2           MISC
 dtype: object, 'LEVEL': 0    1
 1    2
 2    3
 dtype: int64}

In [80]:
grade_lookup2 = pd.DataFrame(grade_lookup)
grade_lookup2

GRADE LEVEL  LEVEL
0   ELEMENTARY      1
1  MIDDLE/HIGH      2
2         MISC      3

In [81]:
# Primeros 5 elementos del campo GRADE LEVEL
df[['GRADE LEVEL']][0:5]

GRADE LEVEL
0  DISTRICT TOTAL
1      ELEMENTARY
2     MIDDLE/HIGH
3  DISTRICT TOTAL
4      ELEMENTARY

In [82]:
# Inner Join
d_sub = df[0:5].join(grade_lookup2.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='inner')
d_sub

LOCATION CODE  COUNTY                                        AREA NAME  \
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT PCT OVERWEIGHT  \
1  NORTHEASTERN NEW YORK    2012-2013            74.0          19.2%   
4  NORTHEASTERN NEW YORK    2012-2013            58.0          16.1%   
2  NORTHEASTERN NEW YORK    2012-2013            50.0          17.6%   

   NO. OBESE PCT OBESE  NO. OVERWEIGHT OR OBESE PCT OVERWEIGHT OR OBESE  \
1       72.0     18.7%                    146.0                   37.9%   
4       89.0     24.7%                    147.0                   40.8%   
2       67.0     23.6%                    117.0                   41.2%   

   GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
1   ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
4   ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
2  MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   

                                          Location 1  LEVEL  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...      1  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...      1  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...      2

In [140]:
#Left Join.
d_sub = df[0:5].join(grade_lookup2.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='left')
d_sub

LOCATION CODE  COUNTY                                        AREA NAME  \
0          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
1          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
2          10402  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   
4          10500  ALBANY                      COHOES CITY SCHOOL DISTRICT   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0          18.5%   
1  NORTHEASTERN NEW YORK    2012-2013            74.0          19.2%   
2  NORTHEASTERN NEW YORK    2012-2013            50.0          17.6%   
3  NORTHEASTERN NEW YORK    2012-2013            84.0          17.2%   
4  NORTHEASTERN NEW YORK    2012-2013            58.0          16.1%   

   NO. OBESE PCT OBESE  NO. OVERWEIGHT OR OBESE PCT OVERWEIGHT OR OBESE  \
0      139.0     20.8%                    263.0                   39.3%   
1       72.0     18.7%                    146.0                   37.9%   
2       67.0     23.6%                    117.0                   41.2%   
3      124.0     25.4%                    208.0                   42.5%   
4       89.0     24.7%                    147.0                   40.8%   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   

                                          Location 1  LEVEL  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    NaN  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    1.0  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    2.0  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...    NaN  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...    1.0

In [141]:
#Full Outer Join.
d_sub = df[0:5].join(grade_lookup2.set_index(['GRADE LEVEL']),on=['GRADE LEVEL'], how='outer')
d_sub

LOCATION CODE  COUNTY                                        AREA NAME  \
0        10402.0  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
3        10500.0  ALBANY                      COHOES CITY SCHOOL DISTRICT   
1        10402.0  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
4        10500.0  ALBANY                      COHOES CITY SCHOOL DISTRICT   
2        10402.0  ALBANY  RAVENA COEYMANS SELKIRK CENTRAL SCHOOL DISTRICT   
4            NaN     NaN                                              NaN   

                  REGION SCHOOL YEARS  NO. OVERWEIGHT PCT OVERWEIGHT  \
0  NORTHEASTERN NEW YORK    2012-2013           124.0          18.5%   
3  NORTHEASTERN NEW YORK    2012-2013            84.0          17.2%   
1  NORTHEASTERN NEW YORK    2012-2013            74.0          19.2%   
4  NORTHEASTERN NEW YORK    2012-2013            58.0          16.1%   
2  NORTHEASTERN NEW YORK    2012-2013            50.0          17.6%   
4                    NaN          NaN             NaN            NaN   

   NO. OBESE PCT OBESE  NO. OVERWEIGHT OR OBESE PCT OVERWEIGHT OR OBESE  \
0      139.0     20.8%                    263.0                   39.3%   
3      124.0     25.4%                    208.0                   42.5%   
1       72.0     18.7%                    146.0                   37.9%   
4       89.0     24.7%                    147.0                   40.8%   
2       67.0     23.6%                    117.0                   41.2%   
4        NaN       NaN                      NaN                     NaN   

      GRADE LEVEL        AREA TYPE  STREET ADDRESS    CITY STATE  ZIP CODE  \
0  DISTRICT TOTAL  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
3  DISTRICT TOTAL  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
1      ELEMENTARY  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
4      ELEMENTARY  SCHOOL DISTRICT      7 BEVAN ST  COHOES    NY   12047.0   
2     MIDDLE/HIGH  SCHOOL DISTRICT  15 MOUNTAIN RD  RAVENA    NY   12143.0   
4            MISC              NaN             NaN     NaN   NaN       NaN   

                                          Location 1  LEVEL  
0  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    NaN  
3  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...    NaN  
1  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    1.0  
4  7 BEVAN ST\nCOHOES, NY 12047\n(42.771285452000...    1.0  
2  15 MOUNTAIN RD\nRAVENA, NY 12143\n(42.47227638...    2.0  
4                                                NaN    3.0

In [142]:
# Group By
df['NO. OBESE'].groupby(d['GRADE LEVEL']).sum()

GRADE LEVEL
DISTRICT TOTAL    127101.0
ELEMENTARY         72880.0
MIDDLE/HIGH        53089.0
Name: NO. OBESE, dtype: float64

In [143]:
df['NO. OBESE'].groupby(df['GRADE LEVEL']).aggregate(sum)

GRADE LEVEL
DISTRICT TOTAL    380851.0
ELEMENTARY        219605.0
MIDDLE/HIGH       160499.0
Name: NO. OBESE, dtype: float64

In [149]:
df['NO. OBESE'].groupby(df['GRADE LEVEL']).std()

GRADE LEVEL
DISTRICT TOTAL    2875.820653
ELEMENTARY        1690.383113
MIDDLE/HIGH       1252.104878
Name: NO. OBESE, dtype: float64